---

- hosts: localhost

  vars_prompt:

    - name: git_name
      prompt: "What name do you want to use for git global author name?"
      default: Jason Hollis
      private: no

    - name: git_email
      prompt: "What email do you want to use for git global email addr?"
      default: jhollis@jdubb.net
      private: no

  roles:
    - { role: ansible-role-dotfiles }
