---

- hosts: localhost

  vars_prompt:

    - name: git_name
      prompt: "What name do you want to use for git global author name?"
      default: Jason Hollis
      private: false

    - name: git_email
      prompt: "What email do you want to use for git global email addr?"
      default: 400979+CodeBleu@users.noreply.github.com
      private: false

  roles:
    - {role: ansible-role-dotfiles}
