---
scenario:
  default:
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    # - idempotence
    - side_effect
    - verify
    - destroy

dependency:
  name: galaxy

driver:
  name: vagrant

provider:
  name: virtualbox

lint: |
  ansible-lint
  yamllint .

platforms:
  - name: vagrant-ubuntu
    box: generic/ubuntu2010
    memory: 512
    cpus: 1
    provider_raw_config_args:
      - "customize [ 'modifyvm', :id, '--uartmode1', 'disconnected' ]"
provisioner:
  name: ansible
verifier:
  name: ansible
