---
scenario:
  default:
  test_sequence:
  - lint
  - destroy
  - dependency
  - syntax
  - create
  - prepare
  - converge
  - idempotence
  - side_effect
  - verify
  - destroy

dependency:
  name: galaxy

driver:
  name: vagrant

provider:
  name: virtualbox

lint: |
  ansible-lint

platforms:
  - name: vagrant-ubuntu
    box: ubuntu/xenial64
    memory: 512
    cpus: 1
    provider_raw_config_args:
      - "customize [ 'modifyvm', :id, '--uartmode1', 'disconnected' ]"
  # - name: vagrant-centos7
  #   box: centos/7
  #   memory: 512
  #   cpus: 1
  #   provider_raw_config_args:
  #     - "customize [ 'modifyvm', :id, '--graphicscontroller', 'vmsvga' ]"
  - name: vagrant-centos8
    box: geerlingguy/centos8
    memory: 512
    cpus: 1
    provider_raw_config_args:
      - "customize [ 'modifyvm', :id, '--graphicscontroller', 'vmsvga' ]"
provisioner:
  name: ansible
verifier:
  name: ansible
